version: '3'

services:
  frontend:
    container_name: dev-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    # Set environment variables directly in the docker-compose file
    environment:
      NEXT_WEBPACK_USEPOLLING: 1

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
