export const data = [
  {
    id: 1,
    name: "Fyyur",
    description:
      "Fyyur is a musical venue and artist booking site that facilitates the discovery and bookings of shows between local performing artists and venues. This site lets you list new artists and venues, discover them, and list shows with artists as a venue owner.",
    stack: [
      "SQLAlchemy",
      "PostgreSQL",
      "Python3",
      "Flask",
      "Flask-Migrate",
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap 3",
    ],
    previewUrl: "#",
    codeUrl: "https://github.com/Souhaib-Benbouzid/Fyuur",
    image: "static/png/projects/Fyyur.png",
  },
  {
    id: 1,
    name: "Fyyur",
    description:
      "Fyyur is a musical venue and artist booking site that facilitates the discovery and bookings of shows between local performing artists and venues. This site lets you list new artists and venues, discover them, and list shows with artists as a venue owner.",
    stack: [
      "SQLAlchemy",
      "PostgreSQL",
      "Python3",
      "Flask",
      "Flask-Migrate",
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap 3",
    ],
    previewUrl: "#",
    codeUrl: "https://github.com/Souhaib-Benbouzid/Fyuur",
    image: "static/png/projects/Fyyur.png",
  },
  {
    id: 1,
    name: "Fyyur",
    description:
      "Fyyur is a musical venue and artist booking site that facilitates the discovery and bookings of shows between local performing artists and venues. This site lets you list new artists and venues, discover them, and list shows with artists as a venue owner.",
    stack: [
      "SQLAlchemy",
      "PostgreSQL",
      "Python3",
      "Flask",
      "Flask-Migrate",
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap 3",
    ],
    previewUrl: "#",
    codeUrl: "https://github.com/Souhaib-Benbouzid/Fyuur",
    image: "static/png/projects/Fyyur.png",
  },
  {
    id: 1,
    name: "Fyyur",
    description:
      "Fyyur is a musical venue and artist booking site that facilitates the discovery and bookings of shows between local performing artists and venues. This site lets you list new artists and venues, discover them, and list shows with artists as a venue owner.",
    stack: [
      "SQLAlchemy",
      "PostgreSQL",
      "Python3",
      "Flask",
      "Flask-Migrate",
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap 3",
    ],
    previewUrl: "#",
    codeUrl: "https://github.com/Souhaib-Benbouzid/Fyuur",
    image: "static/png/projects/Fyyur.png",
  },
];
