version: '3'

services:
  frontend:
    image: sohaibbenbouzid/protfolio-frontend:frontend-latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - web

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    networks:
      - web
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/
    command: certonly --webroot -w /var/www/ -d portfolio.sohaibbenbouzid.com --email souhaib.benbouzid@gmail.com --agree-tos

networks:
  web:
    driver: bridge
