version: '3'

services:
  frontend:
    container_name: frontend
    image: sohaibbenbouzid/protfolio-frontend:frontend-latest
    restart: always
    networks:
      - web

  nginx:
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    networks:
      - web
    image: sohaibbenbouzid/protfolio-frontend:nginx-latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www/:/var/www/
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/
    command: certonly -d portfolio.sohaibbenbouzid.com

networks:
  web:
    driver: bridge
