# Use an official Nginx image as the base image
FROM nginx:latest

# add certificate
# COPY ./conf/nginx.conf /etc/nginx/

# Expose port 80 to the outside world
# EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]