name: Build and push image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    # tags:
    #   - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push portfolio image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio

      - name: Build and push
        uses: docker/bake-action@v4
        with:
          workdir: ./portfolio
          push: true
          files: |
            docker-compose.prod.yml
            ${{ steps.meta.outputs.bake-file }}

      - name: deploy with ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd website && docker compose  down &&  docker compose up --build -d
